Repository fiuba-laboral-v2/back-end, pull requests merged in 2020-03, with the labels that each got.

#28 Feature/36 update detail
  src/graphql/Applicant/mutations.ts
  src/graphql/Career/queries.ts
  src/models/Applicant/Interface.ts
  src/models/Applicant/Model.ts
  src/models/Applicant/Repository.ts
  src/models/Applicant/Serializer.ts
  src/models/Applicant/index.ts
  src/models/Capability/Repository.ts
  src/models/Career/Model.ts
  src/models/CareerApplicant/Model.ts
  src/models/CareerApplicant/Repository.ts
  src/models/Translation/defaultTranslations.ts
  test/graphql/Applicant/mutations/deleteApplicantCapabilities.test.ts
  test/graphql/Applicant/mutations/deleteApplicantCareers.test.ts
  test/graphql/Applicant/mutations/updateApplicant.test.ts
  test/graphql/Career/queries/getCareers.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Applicant/mocks.ts
  test/models/Capability/mocks.ts
  test/models/Career/mocks.ts
Labels: enhancement

#31 Remove unique constrain
  src/migrations/20200318003855-change-career-code-index-in-careers-applicants.ts
  test/models/Applicant/Repository.test.ts
Labels: bug

#32 Feature/86 add applicants list query
  src/graphql/Applicant/queries.ts
  src/models/Applicant/Model.ts
  src/models/Applicant/Repository.ts
  src/models/Applicant/Serializer.ts
  src/models/Career/Model.ts
  src/models/CareerApplicant/Errors/CareerApplicantNotFound.ts
  src/models/CareerApplicant/Errors/index.ts
  src/models/CareerApplicant/Model.ts
  src/models/CareerApplicant/Repository.ts
  src/models/CareerApplicant/Serializer.ts
  src/models/CareerApplicant/index.ts
  src/models/Company/Model.ts
  src/models/Company/Serializer.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Applicant/mocks.ts
Labels: feauture

#33 Use getters to fetch applicant careers and capabilities
  src/models/Applicant/Model.ts
  src/models/Applicant/Repository.ts
  src/models/Applicant/Serializer.ts
  src/models/Capability/Repository.ts
  src/models/CareerApplicant/Model.ts
  src/models/CareerApplicant/Repository.ts
  src/models/CareerApplicant/Serializer.ts
  test/graphql/Applicant/mutations/deleteApplicantCapabilities.test.ts
  test/graphql/Applicant/mutations/deleteApplicantCareers.test.ts
  test/graphql/Applicant/mutations/updateApplicant.test.ts
  test/models/Applicant/Repository.test.ts
Labels: enhancement

#34 Use getter to fetch company photos and phoneNumbers
  src/models/Company/Model.ts
  src/models/Company/Repository.ts
  src/models/Company/Serializer.ts
  test/models/Company/Repository.test.ts
Labels: enhancement

#35 Feat: add getApplicant query to fetch by uuid
  src/graphql/Applicant/queries.ts
  src/models/Applicant/Errors/ApplicantNotFound.ts
  src/models/Applicant/Repository.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/models/Applicant/Repository.test.ts
Labels: refactor

#37 Update translations
  src/models/Translation/defaultTranslations.ts
Labels: enhancement
