Repository fiuba-laboral-v2/back-end, pull requests merged in 2020-04, with the labels that each got.

#36 91 Detalle de postulante
  package.json
  src/graphql/Applicant/Types/Applicant.ts
  src/graphql/Applicant/Types/Section.ts
  src/graphql/Applicant/Types/index.ts
  src/graphql/Applicant/mutations.ts
  src/migrations/20200327181034-create-sections-table.ts
  src/models/Applicant/Errors/ApplicantDoesntHaveSection.ts
  src/models/Applicant/Errors/index.ts
  src/models/Applicant/Interface.ts
  src/models/Applicant/Model.ts
  src/models/Applicant/Repository.ts
  src/models/Applicant/Section/Model.ts
  src/models/Applicant/Section/Repository.ts
  src/models/Applicant/Section/index.ts
  src/models/Applicant/Serializer.ts
  src/models/Applicant/index.ts
  src/models/index.ts
  test/graphql/Applicant/mutations/deleteSection.test.ts
  test/graphql/Applicant/mutations/updateApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/models/Applicant/Model.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Applicant/Section/Model.test.ts
  test/models/Applicant/Section/Repository.test.ts
  test/models/Applicant/mocks.ts
  yarn.lock
Labels: enhancement

#38 Feature/92 use UUID to delete applicant capabilities and careers
  src/graphql/Applicant/mutations.ts
  test/graphql/Applicant/mutations/deleteApplicantCapabilities.test.ts
  test/graphql/Applicant/mutations/deleteApplicantCareers.test.ts
Labels: refactor

#39 Feature/91 detalle de postulante v2
  src/graphql/Applicant/Types/Applicant.ts
  src/graphql/Applicant/Types/Link.ts
  src/graphql/Applicant/Types/index.ts
  src/graphql/Applicant/mutations.ts
  src/migrations/20200331174122-create-applicant-links-table.ts
  src/models/Applicant/Errors/ApplicantDoesntHaveLink.ts
  src/models/Applicant/Errors/index.ts
  src/models/Applicant/Interface.ts
  src/models/Applicant/Link/Interface.ts
  src/models/Applicant/Link/Model.ts
  src/models/Applicant/Link/Repository.ts
  src/models/Applicant/Link/index.ts
  src/models/Applicant/Model.ts
  src/models/Applicant/Repository.ts
  src/models/Applicant/Serializer.ts
  src/models/index.ts
  test/graphql/Applicant/mutations/deleteLink.test.ts
  test/graphql/Applicant/mutations/updateApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/models/Applicant/Link/Model.test.ts
  test/models/Applicant/Link/Repository.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Applicant/Section/Repository.test.ts
Labels: enhancement

#41 Feature/115 offer model
  package.json
  src/migrations/20200405021051-create-offer.ts
  src/models/Offer/Errors/OfferNotFound.ts
  src/models/Offer/Errors/index.ts
  src/models/Offer/Model.ts
  src/models/Offer/Repository.ts
  src/models/Offer/index.ts
  src/models/Offer/interface.ts
  src/models/index.ts
  test/models/Offer/Model.test.ts
  test/models/Offer/Repository.test.ts
  test/models/Offer/mocks.ts
Labels: feature

#42 Add missing translations to applicant edit
  src/models/Translation/defaultTranslations.ts
Labels: feature

#43 Feature/115 offer model validations
  package.json
  src/models/Company/Model.ts
  src/models/Offer/Model.ts
  test/models/Offer/Model.test.ts
  test/models/Offer/mocks.ts
  test/models/User/Model.test.ts
  yarn.lock
Labels: feature

#44 Feature/115 offer section association
  src/migrations/20200407014956-create-offers-sections-table.ts
  src/models/Company/Model.ts
  src/models/Company/Repository.ts
  src/models/Company/index.ts
  src/models/Offer/Interface.ts
  src/models/Offer/Model.ts
  src/models/Offer/OfferSection/Interface.ts
  src/models/Offer/OfferSection/Model.ts
  src/models/Offer/OfferSection/index.ts
  src/models/Offer/Repository.ts
  src/models/Offer/index.ts
  src/models/index.ts
  test/models/Offer/Model.test.ts
  test/models/Offer/OfferSection/Model.test.ts
  test/models/Offer/Repository.test.ts
  test/models/Offer/mocks.ts
Labels: feature

#45 Add capabilities selector translations
  src/models/Translation/defaultTranslations.ts
Labels: feature

#46 Feature/115 offer career association
  src/migrations/20200408220127-create-offers-careers-table.ts
  src/models/Offer/Interface.ts
  src/models/Offer/Model.ts
  src/models/Offer/OfferCareer/Interface.ts
  src/models/Offer/OfferCareer/Model.ts
  src/models/Offer/OfferCareer/index.ts
  src/models/Offer/Repository.ts
  src/models/index.ts
  test/models/Offer/OfferCareer/Model.test.ts
  test/models/Offer/OfferCareer/mocks.ts
  test/models/Offer/Repository.test.ts
  test/models/Offer/mocks.ts
Labels: feature

#47 Feature/115 offer graphql create mutation
  src/graphql/Offer/Mutations/index.ts
  src/graphql/Offer/Mutations/saveOffer.ts
  src/graphql/Offer/Queries/getOfferByUuid.ts
  src/graphql/Offer/Queries/getOffers.ts
  src/graphql/Offer/Queries/index.ts
  src/graphql/Offer/Types/GraphQLOffer.ts
  src/graphql/Offer/Types/GraphQLOfferCareer.ts
  src/graphql/Offer/Types/GraphQLOfferSection.ts
  src/graphql/Offer/Types/index.ts
  src/graphql/Offer/index.ts
  src/graphql/mutations.ts
  src/graphql/queries.ts
  src/graphql/types.ts
  src/models/Offer/Errors/OfferNotFound.ts
  src/models/Offer/Repository.ts
  test/graphql/Offer/mutations/saveOffer.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
Labels: feature

#48 Add company as a return property in offer graphql
  src/graphql/Company/Types/GraphQLCompany.ts
  src/graphql/Company/mutation.ts
  src/graphql/Company/queries.ts
  src/graphql/Offer/Types/GraphQLOffer.ts
  src/models/Company/Serializer.ts
  src/models/Company/index.ts
  test/graphql/Offer/mutations/saveOffer.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
Labels: refactor

#49 Add getCapabilities query
  src/graphql/Applicant/Types/Applicant.ts
  src/graphql/Applicant/Types/index.ts
  src/graphql/Capability/Queries/getCapabilities.ts
  src/graphql/Capability/Queries/index.ts
  src/graphql/Capability/Types/Capability.ts
  src/graphql/Capability/Types/index.ts
  src/graphql/Capability/index.ts
  src/graphql/queries.ts
  src/graphql/types.ts
  src/models/Capability/Repository.ts
  test/graphql/Capability/queries/getCapabilities.test.ts
Labels: feature

#50 Add translations
  src/models/Translation/defaultTranslations.ts
Labels: feature

#51 Refactor mock to avoid repeating unique keys
  test/models/Applicant/Repository.test.ts
  test/models/Career/mocks.ts
Labels: feature

#56 Refactor: Add resolver by field in graphql applicant
  src/graphql/Applicant/Mutations/index.ts
  src/graphql/Applicant/Mutations/saveApplicant.ts
  src/graphql/Applicant/Mutations/updateApplicant.ts
  src/graphql/Applicant/Queries/getApplicant.ts
  src/graphql/Applicant/Queries/getApplicants.ts
  src/graphql/Applicant/Queries/index.ts
  src/graphql/Applicant/Types/Applicant.ts
  src/graphql/Applicant/index.ts
  src/graphql/Applicant/mutations.ts
  src/graphql/Applicant/queries.ts
  test/graphql/Applicant/mutations/deleteApplicantCapabilities.test.ts
  test/graphql/Applicant/mutations/deleteApplicantCareers.test.ts
  test/graphql/Applicant/mutations/deleteLink.test.ts
  test/graphql/Applicant/mutations/deleteSection.test.ts
  test/graphql/Applicant/queries/getApplicantByPadron.test.ts
Labels: refactor

#55 JobApplication
  package.json
  src/migrations/20200412205326-create-job-applications-table.ts
  src/models/Applicant/Model.ts
  src/models/Applicant/Repository.ts
  src/models/JobApplication/Model.ts
  src/models/JobApplication/Repository.ts
  src/models/JobApplication/index.ts
  src/models/Offer/OfferCareer/Model.ts
  src/models/index.ts
  test/models/Applicant/Repository.test.ts
  test/models/Applicant/mocks.ts
  test/models/Career/Repository.test.ts
  test/models/JobApplication/Model.test.ts
  test/models/JobApplication/Repository.test.ts
Labels: feature

#57 Add user uuid to Applicant
  src/graphql/Applicant/Mutations/saveApplicant.ts
  src/graphql/User/Types/GraphQLUserInput.ts
  src/graphql/User/Types/index.ts
  src/graphql/User/mutations.ts
  src/migrations/20200413173812-add-user-id-to-applicant.ts
  src/models/Applicant/Interface.ts
  src/models/Applicant/Model.ts
  src/models/Applicant/Repository.ts
  src/models/User/Repository.ts
  test/graphql/Applicant/mutations/saveApplicant.test.ts
  test/graphql/Applicant/mutations/updateApplicant.test.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/graphql/User/mutations/login.test.ts
  test/graphql/User/mutations/signup.test.ts
  test/graphql/User/queries/me.test.ts
  test/models/Applicant/Link/Model.test.ts
  test/models/Applicant/Link/Repository.test.ts
  test/models/Applicant/Model.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Applicant/Section/Model.test.ts
  test/models/Applicant/Section/Repository.test.ts
  test/models/Applicant/mocks.ts
  test/models/Capability/Model.test.ts
  test/models/Career/Model.test.ts
  test/models/JobApplication/Model.test.ts
  test/models/JobApplication/Repository.test.ts
  test/models/User/Model.test.ts
  test/models/User/Repository.test.ts
Labels: feature

#59 Add translations
  src/models/Translation/defaultTranslations.ts
Labels: feature

#60 Feature/116 graphql job application
  src/graphql/JobApplication/Mutations/index.ts
  src/graphql/JobApplication/Mutations/saveJobApplication.ts
  src/graphql/JobApplication/Types/GraphQLJobApplication.ts
  src/graphql/JobApplication/Types/index.ts
  src/graphql/JobApplication/index.ts
  src/graphql/mutations.ts
  src/graphql/types.ts
  src/models/User/Model.ts
  src/models/User/index.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/models/User/Model.test.ts
Labels: feature

#58 [TPP 92] nuevo update de applicant
  src/models/Applicant/Errors/ApplicantDoesntHaveLink.ts
  src/models/Applicant/Errors/ApplicantDoesntHaveSection.ts
  src/models/Applicant/Errors/index.ts
  src/models/Applicant/Link/Repository.ts
  src/models/Applicant/Model.ts
  src/models/Applicant/Repository.ts
  src/models/Applicant/Section/Repository.ts
  src/models/ApplicantCapability/Repository.ts
  src/models/CareerApplicant/Repository.ts
  test/graphql/Applicant/mutations/updateApplicant.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/CareerApplicant/Model.test.ts
Labels: refactor

#61 Feature/116 add has aplied field
  src/graphql/JobApplication/Mutations/saveJobApplication.ts
  src/graphql/Offer/Types/GraphQLOffer.ts
  src/graphql/fieldTypes.ts
  src/models/JobApplication/Repository.ts
  test/graphql/ApolloTestClient.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/User/mutations/login.test.ts
  test/graphql/User/queries/me.test.ts
  test/models/JobApplication/Repository.test.ts
Labels: feature

#62 Add translations
  src/models/Translation/defaultTranslations.ts
Labels: feature

#64 Add custom error for bad credentials
  src/graphql/User/Errors/BadCredentials.ts
  src/graphql/User/Errors/index.ts
  src/graphql/User/mutations.ts
  test/graphql/User/mutations/login.test.ts
Labels: feature

#54 Fix capability description migration down function
  package.json
  src/migrations/20200412161744-change-capability-description-to-citext.ts
Labels: refactor

#63 Add translations with key - value
  src/graphql/Translation/Types/Translation.ts
  src/graphql/Translation/Types/index.ts
  src/graphql/Translation/queries.ts
  src/graphql/types.ts
  src/models/Translation/TranslationRepository.ts
  src/models/Translation/defaultTranslations.ts
  test/graphql/Translation/queries/getTranslations.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Translation/TranslationRepository.test.ts
Labels: feature

#67 Add graphql mapped errors
  .travis.yml
  package.json
  src/FormatErrors/ErrorMaps/ForeignKeyConstraintMapper.ts
  src/FormatErrors/ErrorMaps/Generic.ts
  src/FormatErrors/ErrorMaps/IMapItem.ts
  src/FormatErrors/ErrorMaps/UniqueConstraintMapper.ts
  src/FormatErrors/ErrorMaps/index.ts
  src/FormatErrors/index.ts
  src/graphql/Errors/AuthenticationError.ts
  src/graphql/Errors/UnauthorizedError.ts
  src/graphql/Errors/index.ts
  src/graphql/JobApplication/Mutations/saveJobApplication.ts
  src/graphql/Offer/Types/GraphQLOffer.ts
  src/graphql/User/Errors/BadCredentialsError.ts
  src/graphql/User/Errors/index.ts
  src/graphql/User/mutations.ts
  src/graphql/User/queries.ts
  src/models/Applicant/Repository.ts
  src/models/Career/Repository.ts
  src/models/Company/Repository.ts
  src/models/Offer/Repository.ts
  src/models/Translation/Errors/MissingTranslationError.ts
  src/models/Translation/Errors/index.ts
  src/models/Translation/TranslationRepository.ts
  src/models/Translation/defaultTranslations.ts
  src/models/User/Errors/UserNotFoundError.ts
  src/models/User/Errors/index.ts
  src/models/User/Repository.ts
  src/models/User/index.ts
  src/server.ts
  test/graphql/ApolloTestClient.ts
  test/graphql/Applicant/mutations/saveApplicant.test.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Capability/queries/getCapabilities.test.ts
  test/graphql/Career/mutations/saveCareer.test.ts
  test/graphql/Career/queries/getCareerByCode.test.ts
  test/graphql/Company/mutations/saveCompany.test.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/Offer/mutations/saveOffer.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Translation/queries/getTranslations.test.ts
  test/graphql/User/mutations/login.test.ts
  test/graphql/User/queries/me.test.ts
  test/models/Translation/TranslationRepository.test.ts
  test/models/User/Repository.test.ts
  yarn.lock
Labels: feature
