Repository fiuba-laboral-v2/back-end, pull requests merged in 2020-07, with the labels that each got.

#142 WIP: Feature/207 get pending applicants
  src/graphql/Approvable/Types/GraphQLApprovable.ts
  src/graphql/Company/Types/GraphQLCompany.ts
  src/migrations/20200606221856-create-approval-status-enum-type.ts
  src/migrations/20200606221857-add-approval-status-to-companies.ts
  src/migrations/20200627015120-add-approval-status-to-applicants.ts
  src/models/Applicant/Repository.ts
  src/models/Approvable/ApprovableModels.ts
  src/models/Approvable/Model.ts
  src/models/Approvable/Repository.ts
  src/models/Approvable/TableNameColumn.ts
  src/models/Approvable/findApprovableQuery.ts
  src/models/Approvable/findPendingQuery.ts
  src/models/Approvable/index.ts
  test/config/customMatchers/toBeSortedBy.ts
  test/config/jest.setup.ts
  test/generators/Applicant/index.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Approvable/queries/getPendingEntities.test.ts
  test/graphql/JobApplication/queries/getMyLatestJobApplications.test.ts
  test/models/Applicant/ApplicantApprovalEvent/Repository.test.ts
  test/models/Approvable/Repository.test.ts
  test/models/Approvable/findApprovableQuery.test.ts
  test/models/Approvable/findPendingQuery.test.ts
  test/models/Company/Repository.test.ts
  test/models/JobApplication/Repository.test.ts
  test/types/index.d.ts
Labels: feature

#145 Refactor findApprovableQuery internal method and move them to groupTa…
  src/models/Approvable/findApprovableQuery.ts
  src/models/Approvable/groupTableNamesByColumn.ts
  test/config/customMatchers/toEqualIgnoringSpacing.ts
  test/config/jest.setup.ts
  test/models/Approvable/findApprovableQuery.test.ts
  test/models/Approvable/findPendingQuery.test.ts
  test/models/Approvable/groupTableNamesByColumn.test.ts
  test/types/index.d.ts
Labels: refactor

#146 Add applicantIconTitle translation in adminMenu translationGroup
  src/models/Translation/defaultTranslations.ts
Labels: feature

#147 Add approvalActions translations group
  src/models/Translation/defaultTranslations.ts
Labels: feature

#148 Add permissions check for approved applicants
  src/graphql/Applicant/Permissions.ts
  src/graphql/Career/Permissions.ts
  src/graphql/Company/Permissions.ts
  src/graphql/JobApplication/Permissions.ts
  src/graphql/Offer/Permissions.ts
  src/graphql/Rules/isAdmin.ts
  src/graphql/Rules/isApplicant.ts
  src/graphql/Rules/isApprovedApplicant.ts
  src/graphql/Rules/isCompanyUser.ts
  src/graphql/Rules/isFromApprovedCompany.ts
  src/graphql/Rules/isUser.ts
  src/graphql/Rules/rule.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/graphql/Career/mutations/saveCareer.test.ts
  test/graphql/Company/queries/getCompanies.test.ts
  test/graphql/Company/queries/getCompanyByUuid.test.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/Offer/mutations/editOffer.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
  test/mocks/interfaces.ts
  test/mocks/testClientFactory.ts
  test/mocks/user.ts
  test/models/Applicant/Model.test.ts
  test/models/CompanyUser/Model.test.ts
  test/models/User/Model.test.ts
Labels: feature

#149 Feature/209 get pending entities filter
  src/graphql/Approvable/Queries/getPendingEntities.ts
  src/graphql/Approvable/Types/GraphQLApprovableEntityType.ts
  src/graphql/Approvable/Types/index.ts
  src/models/Approvable/ApprovableModels.ts
  src/models/Approvable/Interfaces.ts
  src/models/Approvable/Model.ts
  src/models/Approvable/Repository.ts
  src/models/Approvable/TableNameColumn.ts
  src/models/Approvable/findApprovableQuery.ts
  src/models/Approvable/findPendingQuery.ts
  src/models/Approvable/groupTableNamesByColumn.ts
  src/models/Approvable/index.ts
  src/models/Company/Model.ts
  test/config/customMatchers/toEqualIgnoringSpacing.ts
  test/graphql/Approvable/queries/getPendingEntities.test.ts
  test/models/Approvable/Repository.test.ts
  test/models/Approvable/findApprovableQuery.test.ts
  test/models/Approvable/findPendingQuery.test.ts
  test/models/Approvable/groupTableNamesByColumn.test.ts
Labels: feature

#152 Fix/209 pending entities filter
  src/graphql/Approvable/Queries/getPendingEntities.ts
  src/models/Approvable/Errors/ApprovableEntityTypesIsEmptyError.ts
  src/models/Approvable/Errors/index.ts
  src/models/Approvable/Interfaces.ts
  src/models/Approvable/Repository.ts
  src/models/Approvable/findApprovableQuery.ts
  test/config/customMatchers/toThrowErrorWithMessage.ts
  test/graphql/Approvable/queries/getPendingEntities.test.ts
  test/models/Approvable/Repository.test.ts
  test/models/Approvable/findApprovableQuery.test.ts
  test/models/Approvable/findPendingQuery.test.ts
Labels: fix

#151 Add iso date to graphql
  package-lock.json
  package.json
  src/graphql/Applicant/Types/Applicant.ts
  src/graphql/Company/Types/GraphQLCompany.ts
  src/graphql/JobApplication/Types/GraphQLJobApplication.ts
  src/graphql/Offer/Types/GraphQLOffer.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Company/queries/getCompanyByUuid.test.ts
  test/graphql/JobApplication/queries/getMyLatestJobApplications.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  yarn.lock
Labels: feature

#153 Add title translation in typeFilterMenu translationGroup
  src/models/Translation/defaultTranslations.ts
Labels: feature

#155 Add adminApplicantMainTitle and adminApplicantDetails translation groups
  src/models/Translation/defaultTranslations.ts
Labels: feature

#156 updateApplicantApprovalStatus mutation
  src/graphql/Applicant/Mutations/index.ts
  src/graphql/Applicant/Mutations/updateApplicantApprovalStatus.ts
  src/graphql/Applicant/Permissions.ts
  test/graphql/Applicant/mutations/updateCompanyApprovalStatus.test.ts
Labels: feature

#157 Feature/218 get approvables query
  src/graphql/Approvable/Permissions.ts
  src/graphql/Approvable/Queries/getApprovables.ts
  src/graphql/Approvable/Queries/getPendingEntities.ts
  src/graphql/Approvable/Queries/index.ts
  src/models/Approvable/Errors/StatusesIsEmptyError.ts
  src/models/Approvable/Errors/index.ts
  src/models/Approvable/Interfaces.ts
  src/models/Approvable/Repository.ts
  src/models/Approvable/findApprovablesQuery.ts
  src/models/Approvable/findPendingQuery.ts
  test/generators/Applicant/index.ts
  test/generators/Company/index.ts
  test/generators/GenericGenerator/index.ts
  test/generators/Offer/index.ts
  test/graphql/Approvable/queries/getApprovables.test.ts
  test/graphql/Approvable/queries/getPendingEntities.test.ts
  test/models/Approvable/Repository.test.ts
  test/models/Approvable/findApprovableQuery.test.ts
  test/models/Approvable/findApprovablesQuery.test.ts
  test/models/Approvable/findPendingQuery.test.ts
Labels: feature

#158 Feature/218 rename aprovables
  src/graphql/AdminTask/Permissions.ts
  src/graphql/AdminTask/Queries/getAdminTasks.ts
  src/graphql/AdminTask/Queries/index.ts
  src/graphql/AdminTask/Types/GraphQLAdminTask.ts
  src/graphql/AdminTask/Types/GraphQLAdminTaskType.ts
  src/graphql/AdminTask/Types/index.ts
  src/graphql/AdminTask/index.ts
  src/graphql/Approvable/Permissions.ts
  src/graphql/Approvable/Queries/getApprovables.ts
  src/graphql/Approvable/Queries/index.ts
  src/graphql/Approvable/Types/GraphQLApprovableEntityType.ts
  src/graphql/Approvable/Types/index.ts
  src/graphql/permissionShield.ts
  src/graphql/queries.ts
  src/graphql/types.ts
  src/models/AdminTask/Errors/AdminTaskTypesIsEmptyError.ts
  src/models/AdminTask/Errors/StatusesIsEmptyError.ts
  src/models/AdminTask/Errors/index.ts
  src/models/AdminTask/Interfaces.ts
  src/models/AdminTask/Model.ts
  src/models/AdminTask/Repository.ts
  src/models/AdminTask/findAdminTasksQuery.ts
  src/models/AdminTask/groupTableNamesByColumn.ts
  src/models/AdminTask/index.ts
  src/models/Approvable/Errors/ApprovableEntityTypesIsEmptyError.ts
  src/models/Approvable/Errors/index.ts
  src/models/Approvable/Interfaces.ts
  src/models/Approvable/Repository.ts
  src/models/Approvable/findApprovablesQuery.ts
  src/models/Approvable/groupTableNamesByColumn.ts
  test/graphql/AdminTask/queries/getAdminTasks.test.ts
  test/models/AdminTask/Repository.test.ts
  test/models/AdminTask/findAdminTasksQuery.test.ts
  test/models/AdminTask/groupTableNamesByColumn.test.ts
Labels: refactor

#159 Add statusFilterMenu translation group
  src/models/Translation/defaultTranslations.ts
Labels: feature

#160 Add pending translation to adminActions translationGroup
  src/models/Translation/defaultTranslations.ts
Labels: feature

#162 Feature/226 label
  src/models/Translation/defaultTranslations.ts
Labels: feature

#164 Add pending translation for approvalActions translationGroup
  src/models/Translation/defaultTranslations.ts
Labels: fix

#166 Rename Applicant.ts to GraphQLApplicant.ts
  src/graphql/AdminTask/Types/GraphQLAdminTask.ts
  src/graphql/Applicant/Mutations/saveApplicant.ts
  src/graphql/Applicant/Mutations/updateApplicantApprovalStatus.ts
  src/graphql/Applicant/Mutations/updateCurrentApplicant.ts
  src/graphql/Applicant/Queries/getApplicant.ts
  src/graphql/Applicant/Queries/getApplicants.ts
  src/graphql/Applicant/Types/GraphQLApplicant.ts
  src/graphql/Applicant/Types/index.ts
  src/graphql/JobApplication/Types/GraphQLJobApplication.ts
  src/graphql/User/Types/GraphQLUser.ts
Labels: refactor

#167 Fix/228 admin task updated at
  src/graphql/Applicant/Types/GraphQLApplicant.ts
  src/graphql/Company/Types/GraphQLCompany.ts
  src/models/Translation/defaultTranslations.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Company/queries/getCompanyByUuid.test.ts
Labels: fix
