Repository fiuba-laboral-v2/back-end, pull requests merged in 2020-05, with the labels that each got.

#68 Migrate company id to uuid
  src/FormatErrors/ErrorMaps/ForeignKeyConstraintMapper.ts
  src/graphql/Company/Types/GraphQLCompany.ts
  src/graphql/Company/queries.ts
  src/graphql/Offer/Mutations/saveOffer.ts
  src/migrations/20200129005352-create-companies-table.ts
  src/migrations/20200129005352-create-company-profile.ts
  src/migrations/20200129015952-create-company-phone-numbers.ts
  src/migrations/20200129015952-create-company-profile-phone-numbers.ts
  src/migrations/20200131064953-create-company-photos.ts
  src/migrations/20200131064953-create-company-profile-photos.ts
  src/migrations/20200213060731-add-website-to-company-profile.ts
  src/migrations/20200214003023-add-email-to-company-profile.ts
  src/migrations/20200214011030-change-logo-data-type-from-company-profile.ts
  src/migrations/20200214025657-change-photo-data-type-from-company-profile-photos.ts
  src/migrations/20200216202241-rename-company-profiles-to-companies.ts
  src/migrations/20200216204218-rename-company-profile-phone-numbers-to-company-phone-numbers.ts
  src/migrations/20200216205119-rename-company-profile-photos-to-company-photos.ts
  src/migrations/20200216213349-rename-company-profile-id-to-company-id-from-company-photos.ts
  src/migrations/20200216214036-create-rename-company-profile-id-to-company-id-from-company-phone-numbers.ts
  src/migrations/20200217020550-add-references-to-company-id-from-company-phone-numbers.ts
  src/migrations/20200217022308-add-references-to-company-id-from-company-photos.ts
  src/migrations/20200224162340-change-cuit-to-unique-from-company.ts
  src/migrations/20200405021051-create-offer.ts
  src/models/Company/Errors/CompanyNotFoundError.ts
  src/models/Company/Model.ts
  src/models/Company/Repository.ts
  src/models/CompanyPhoneNumber/Model.ts
  src/models/CompanyPhoto/Model.ts
  src/models/Offer/Interface.ts
  src/models/Offer/Model.ts
  test/graphql/Company/queries/getCompanyById.test.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/Offer/mutations/saveOffer.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
  test/models/Company/Model.test.ts
  test/models/Company/Repository.test.ts
  test/models/CompanyPhoneNumber/Model.test.ts
  test/models/CompanyPhoto/Model.test.ts
  test/models/JobApplication/Model.test.ts
  test/models/JobApplication/Repository.test.ts
  test/models/Offer/Model.test.ts
  test/models/Offer/OfferCareer/Model.test.ts
  test/models/Offer/OfferSection/Model.test.ts
  test/models/Offer/Repository.test.ts
  test/models/Offer/mocks.ts
Labels: refactor

#69 fix migrations: Move migrations to one file for each table
  config/database.json
  src/FormatErrors/ErrorMaps/UniqueConstraintMapper.ts
  src/migrations/20200203222832-create-career-table.ts
  src/migrations/20200204234523-create-users.ts
  src/migrations/20200204234524-create-applicant-table.ts
  src/migrations/20200205200615-create-career-applicant-table.ts
  src/migrations/20200208173310-create-capability-table.ts
  src/migrations/20200208173450-create-applicant-capability-table.ts
  src/migrations/20200219225940-change-type-career-code-to-text.ts
  src/migrations/20200219235145-change-applicant-description.ts
  src/migrations/20200220210231-move-credits-to-career-applicant.ts
  src/migrations/20200311203056-change-career-code-in-career-applicant-table.ts
  src/migrations/20200318003855-change-career-code-index-in-careers-applicants.ts
  src/migrations/20200412161744-change-capability-description-to-citext.ts
  src/migrations/20200413173812-add-user-id-to-applicant.ts
Labels: refactor

#70 Feature/138 seed database
  .gitignore
  .sequelizerc
  package.json
  src/seeders/20200503163557-add-careers.ts
  src/seeders/20200503171339-add-companies.ts
  src/seeders/20200503182603-add-offers.ts
  src/seeders/20200503185338-add-capabilities.ts
  src/seeders/20200503190711-add-users.ts
  src/seeders/20200503190712-add-applicants.ts
  src/seeders/constants/careerCodes.ts
  src/seeders/constants/uuids.ts
  src/seeders/tsconfig.json
Labels: feature

#71 Feature/138 migrate name and surname to users table
  src/graphql/Applicant/Mutations/saveApplicant.ts
  src/graphql/Applicant/Mutations/updateApplicant.ts
  src/graphql/Applicant/Types/Applicant.ts
  src/graphql/User/Types/GraphQLUser.ts
  src/graphql/User/Types/GraphQLUserCreateInput.ts
  src/graphql/User/Types/GraphQLUserUpdateInput.ts
  src/graphql/User/Types/index.ts
  src/migrations/20200204234523-create-users.ts
  src/migrations/20200204234524-create-applicant-table.ts
  src/models/Applicant/Interface.ts
  src/models/Applicant/Model.ts
  src/models/Applicant/Repository.ts
  src/models/Applicant/Serializer.ts
  src/models/Applicant/index.ts
  src/models/User/Interface.ts
  src/models/User/Model.ts
  src/models/User/Repository.ts
  src/models/User/index.ts
  src/seeders/20200503190711-add-users.ts
  src/seeders/20200503190712-add-applicants.ts
  test/graphql/Applicant/mutations/saveApplicant.test.ts
  test/graphql/Applicant/mutations/updateApplicant.test.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/User/mutations/login.test.ts
  test/graphql/User/queries/me.test.ts
  test/models/Applicant/Link/Model.test.ts
  test/models/Applicant/Link/Repository.test.ts
  test/models/Applicant/Model.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Applicant/Section/Model.test.ts
  test/models/Applicant/Section/Repository.test.ts
  test/models/Applicant/mocks.ts
  test/models/Capability/Model.test.ts
  test/models/Capability/Repository.test.ts
  test/models/Career/Model.test.ts
  test/models/User/Model.test.ts
  test/models/User/Repository.test.ts
Labels: refactor

#73 Fix company description type
  src/migrations/20200129005352-create-companies-table.ts
  src/models/Company/Model.ts
  test/models/Company/Repository.test.ts
Labels: fix

#74 validations for links
  src/FormatErrors/ErrorMaps/UniqueConstraintMapper.ts
  src/graphql/Applicant/Types/Applicant.ts
  src/graphql/Applicant/Types/Link.ts
  src/migrations/20200331174122-create-applicant-links-table.ts
  src/models/Applicant/Link/Interface.ts
  src/models/Applicant/Link/Model.ts
  src/models/Applicant/Link/Repository.ts
  test/graphql/Applicant/mutations/updateApplicant.test.ts
  test/models/Applicant/Link/Model.test.ts
  test/models/Applicant/Link/Repository.test.ts
Labels: feature

#75 Feature/138 fix company phone numbers
  src/graphql/Company/Types/GraphQLCompany.ts
  src/graphql/Company/mutation.ts
  src/migrations/20200129015952-create-company-phone-numbers.ts
  src/models/Company/Interface.ts
  src/models/Company/Repository.ts
  src/models/CompanyPhoneNumber/Model.ts
  src/models/CompanyPhoneNumber/Repository.ts
  src/models/CompanyPhoto/Repository.ts
  src/seeders/20200503171339-add-companies.ts
  test/graphql/Company/mutations/saveCompany.test.ts
  test/graphql/Company/queries/getCompanies.test.ts
  test/graphql/Company/queries/getCompanyByUuid.test.ts
  test/models/Applicant/Link/Repository.test.ts
  test/models/Company/Repository.test.ts
  test/models/Company/mocks.ts
  test/models/CompanyPhoneNumber/Model.test.ts
  test/models/CompanyPhoneNumber/Repository.test.ts
Labels: refactor

#76 Add phone number validation
  package.json
  src/models/Company/Repository.ts
  src/models/CompanyPhoneNumber/Model.ts
  test/graphql/Company/mutations/saveCompany.test.ts
  test/graphql/Company/queries/getCompanyByUuid.test.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/Offer/mutations/saveOffer.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
  test/models/Applicant/Link/Repository.test.ts
  test/models/Company/Model.test.ts
  test/models/Company/Repository.test.ts
  test/models/Company/mocks.ts
  test/models/CompanyPhoneNumber/Model.test.ts
  test/models/CompanyPhoneNumber/Repository.test.ts
  test/models/JobApplication/Model.test.ts
  test/models/JobApplication/Repository.test.ts
  test/models/Offer/Model.test.ts
  test/models/Offer/OfferCareer/Model.test.ts
  test/models/Offer/OfferSection/Model.test.ts
  test/models/Offer/Repository.test.ts
  test/models/User/Model.test.ts
  yarn.lock
Labels: feature

#77 Feature/153 add custom matchers
  .gitignore
  .travis.yml
  jest.config.js
  package.json
  test/config/customMatchers/toBeAggregateError.ts
  test/config/customMatchers/toBeAggregateErrorIncluding.ts
  test/config/customMatchers/toBeBulkRecordError.ts
  test/config/customMatchers/toThrowBulkRecordErrorIncluding.ts
  test/config/customMatchers/toThrowErrorWithMessage.ts
  test/config/jest.setup.ts
  test/graphql/Applicant/mutations/saveApplicant.test.ts
  test/graphql/Applicant/mutations/updateApplicant.test.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/graphql/Capability/queries/getCapabilities.test.ts
  test/graphql/Career/mutations/saveCareer.test.ts
  test/graphql/Career/queries/getCareerByCode.test.ts
  test/graphql/Career/queries/getCareers.test.ts
  test/graphql/Company/mutations/saveCompany.test.ts
  test/graphql/Company/queries/getCompanyByUuid.test.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/Offer/mutations/saveOffer.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
  test/graphql/Translation/queries/getTranslations.test.ts
  test/graphql/User/mutations/login.test.ts
  test/graphql/User/queries/me.test.ts
  test/models/Applicant/Link/Repository.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Applicant/Section/Repository.test.ts
  test/models/Company/Model.test.ts
  test/models/Company/Repository.test.ts
  test/models/CompanyPhoneNumber/Model.test.ts
  test/models/CompanyPhoneNumber/Repository.test.ts
  test/models/Offer/Repository.test.ts
  test/models/Offer/mocks.ts
  test/tsconfig.json
  test/types/Constructable.ts
  test/types/index.d.ts
  tsconfig.json
Labels: feature

#79 Add translations
  src/models/Translation/defaultTranslations.ts
Labels: feature

#81 Feature/38 company signup
  src/models/Company/Model.ts
  src/models/Translation/defaultTranslations.ts
Labels: feature

#83 Add translations to create offer page
  src/models/Translation/defaultTranslations.ts
Labels: feature

#84 Add companyEmail translation to companySignUp group
  src/models/Translation/defaultTranslations.ts
Labels: feature

#78 75 Permisos
  package.json
  src/JWT.ts
  src/graphql/JobApplication/Mutations/saveJobApplication.ts
  src/graphql/JobApplication/Types/GraphQLJobApplication.ts
  src/graphql/JobApplication/index.ts
  src/graphql/JobApplication/permissions.ts
  src/graphql/Offer/Types/GraphQLOffer.ts
  src/graphql/Offer/permissions.ts
  src/graphql/Schema.ts
  src/graphql/User/index.ts
  src/graphql/User/permissions.ts
  src/graphql/User/queries.ts
  src/graphql/permissionShield.ts
  src/graphql/rules.ts
  src/graphqlContext.ts
  src/models/JobApplication/Repository.ts
  src/server.ts
  test/graphql/ApolloTestClient.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/User/mutations/login.test.ts
  test/mocks/login.ts
  test/mocks/user.ts
  test/models/JobApplication/Repository.test.ts
  yarn.lock
Labels: feature

#86 Add CompanyLogoInput translations
  src/models/Translation/defaultTranslations.ts
Labels: feature

#87 Add translations for job offer apply
  src/models/Translation/defaultTranslations.ts
Labels: feature

#92 add companyUuid in decode token
  src/JWT.ts
  test/graphql/User/mutations/login.test.ts
  test/mocks/user.ts
Labels: fix

#91 Add getJobApplicationsByCompany to retrieve job applications of …
  src/graphql/JobApplication/Permissions.ts
  src/graphql/JobApplication/Queries/getJobApplicationsByCompany.ts
  src/graphql/JobApplication/Queries/index.ts
  src/graphql/JobApplication/Types/GraphQLJobApplication.ts
  src/graphql/JobApplication/index.ts
  src/graphql/queries.ts
  src/models/JobApplication/Repository.ts
  src/models/Offer/Repository.ts
  src/models/Translation/defaultTranslations.ts
  test/graphql/Company/mutations/createCompany.test.ts
  test/graphql/Company/queries/getCompanyByUuid.test.ts
  test/graphql/JobApplication/queries/getJobApplicationsByCompany.test.ts
  test/models/Applicant/mocks.ts
  test/models/Company/mocks.ts
  test/models/JobApplication/Model.test.ts
  test/models/JobApplication/Repository.test.ts
Labels: feature

#93 Add data to seed
  src/seeders/20200503190711-add-users.ts
  src/seeders/20200503190713-add-companies.ts
  src/seeders/20200503190714-add-offers.ts
  src/seeders/constants/uuids.ts
Labels: feature

#96 Feature/158 latest job application by company
  src/graphql/JobApplication/Permissions.ts
  src/graphql/JobApplication/Queries/getMyLatestJobApplications.ts
  src/graphql/JobApplication/Queries/index.ts
  src/graphql/JobApplication/Types/GraphQLJobApplication.ts
  src/models/JobApplication/Repository.ts
  test/graphql/JobApplication/queries/getMyLatestJobApplications.test.ts
  test/models/JobApplication/Repository.test.ts
Labels: feature

#95 Refactor createOffer mutation to use currentCompanyUser context
  src/graphql/Offer/Mutations/createOffer.ts
  src/graphql/Offer/Permissons.ts
  src/models/Translation/defaultTranslations.ts
  test/graphql/Offer/mutations/createOffer.test.ts
Labels: feature

#94 Add company to currentUser query
  src/graphql/User/Types/GraphQLUser.ts
  src/models/User/Model.ts
  test/graphql/User/queries/getCurrentUser.test.ts
Labels: feature

#97 75 permisos v4
  src/graphql/Applicant/Permissions.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/graphql/User/mutations/login.test.ts
  test/mocks/interfaces.ts
  test/mocks/testClientFactory.ts
  test/mocks/user.ts
Labels: feature

#99 Add applicant to seed info
  src/seeders/20200503190707-add-users.ts
  src/seeders/20200503190708-add-companies.ts
  src/seeders/20200503190710-add-offers.ts
  src/seeders/20200503190712-add-applicants.ts
  src/seeders/constants/uuids.ts
Labels: feature

#101 Add myCompanyProfile translation
  src/models/Translation/defaultTranslations.ts
Labels: feature

#103 Change updateApplicant by uuid to updateCurrentApplicant
  src/graphql/Applicant/Mutations/index.ts
  src/graphql/Applicant/Mutations/updateCurrentApplicant.ts
  src/graphql/Applicant/Permissions.ts
  src/models/Translation/defaultTranslations.ts
  test/graphql/Applicant/mutations/updateCurrentApplicant.test.ts
  test/graphql/Translation/queries/getTranslations.test.ts
Labels: refactor

#104 Remove unused translations
  src/models/Translation/defaultTranslations.ts
Labels: feature

#107 Feature/42 update company profile
  src/graphql/Company/Mutations/index.ts
  src/graphql/Company/Mutations/updateCurrentCompany.ts
  src/graphql/Company/Permissions.ts
  src/models/Company/Interface.ts
  src/models/Company/Repository.ts
  src/models/Company/index.ts
  src/models/Translation/defaultTranslations.ts
  test/graphql/Company/mutations/updateCurrentCompany.test.ts
  test/mocks/user.ts
  test/models/Company/Repository.test.ts
  test/models/Company/mocks.ts
  test/models/JobApplication/Repository.test.ts
Labels: feature

#110 Feature/167 generators
  test/generators/Applicant/index.ts
  test/generators/Applicant/withMinimumData.ts
  test/generators/Company/completeData.ts
  test/generators/Company/cuitGenerator.ts
  test/generators/Company/index.ts
  test/generators/Company/withMinimumData.ts
  test/generators/types.ts
  test/graphql/Company/mutations/createCompany.test.ts
  test/mocks/user.ts
  test/models/Applicant/mocks.ts
  test/models/Company/Model.test.ts
  test/models/Company/Repository.test.ts
  test/models/Company/mocks.ts
  test/models/JobApplication/Model.test.ts
  test/models/JobApplication/Repository.test.ts
  test/models/Offer/Model.test.ts
  test/models/Offer/Repository.test.ts
  test/models/Offer/mocks.ts
Labels: feature

#111 Rename table from CareersAppliants to ApplicantCareers
  src/FormatErrors/ErrorMaps/ForeignKeyConstraintMapper.ts
  src/FormatErrors/ErrorMaps/UniqueConstraintMapper.ts
  src/graphql/Applicant/Types/Applicant.ts
  src/migrations/20200205200615-create-career-applicant-table.ts
  src/models/Applicant/Model.ts
  src/models/Applicant/Repository.ts
  src/models/ApplicantCareer/Errors/ApplicantCareerNotFound.ts
  src/models/ApplicantCareer/Errors/index.ts
  src/models/ApplicantCareer/Model.ts
  src/models/ApplicantCareer/Repository.ts
  src/models/ApplicantCareer/Serializer.ts
  src/models/ApplicantCareer/index.ts
  src/models/Career/Model.ts
  src/models/Career/Repository.ts
  src/models/CareerApplicant/Errors/CareerApplicantNotFound.ts
  src/models/CareerApplicant/Errors/index.ts
  src/models/CareerApplicant/Serializer.ts
  src/models/CareerApplicant/index.ts
  src/models/index.ts
  src/seeders/20200503190712-add-applicants.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/CareerApplicant/Model.test.ts
Labels: feature

#112 Validate company email and website
  package.json
  src/models/Company/Model.ts
  test/graphql/Company/mutations/updateCurrentCompany.test.ts
  test/models/Company/Model.test.ts
  test/models/Company/Repository.test.ts
  yarn.lock
Labels: feature

#113 Refactor/avoid truncating database before each test
  test/generators/Applicant/index.ts
  test/generators/Applicant/withMinimumData.ts
  test/generators/Career/index.ts
  test/graphql/Applicant/mutations/saveApplicant.test.ts
  test/graphql/JobApplication/queries/getMyLatestJobApplications.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Applicant/mocks.ts
  test/models/Capability/mocks.ts
  test/models/Career/mocks.ts
Labels: refactor

#114 Refactor/avoid truncating database before each test v2
  test/generators/Career/careerGenerator.ts
  test/generators/Career/index.ts
  test/graphql/Applicant/mutations/saveApplicant.test.ts
  test/graphql/Applicant/mutations/updateCurrentApplicant.test.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/graphql/Career/mutations/saveCareer.test.ts
  test/graphql/Career/queries/getCareerByCode.test.ts
  test/graphql/Career/queries/getCareers.test.ts
  test/graphql/Offer/mutations/createOffer.test.ts
  test/graphql/Offer/queries/getMyOffers.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Career/Model.test.ts
  test/models/Career/Repository.test.ts
Labels: refactor

#115 Refactor/avoid truncating database before each test v3
  test/generators/Career/careerData.ts
  test/generators/Career/index.ts
  test/generators/Offer/index.ts
  test/generators/Offer/interfaces.ts
  test/generators/Offer/offerGenericGenerator.ts
  test/generators/Offer/withObligatoryData.ts
  test/generators/Offer/withOneSection.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/JobApplication/queries/getMyLatestJobApplications.test.ts
  test/graphql/Offer/mutations/createOffer.test.ts
  test/graphql/Offer/mutations/editOffer.test.ts
  test/graphql/Offer/queries/getMyOffers.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
  test/models/Career/mocks.ts
  test/models/JobApplication/Repository.test.ts
  test/models/Offer/OfferCareer/Model.test.ts
  test/models/Offer/OfferCareer/mocks.ts
  test/models/Offer/OfferSection/Model.test.ts
  test/models/Offer/Repository.test.ts
  test/models/Offer/mocks.ts
Labels: refactor
