Repository fiuba-laboral-v2/back-end, pull requests merged in 2020-09, with the labels that each got.

#226 Fix/270 redirect to login
  src/graphql/User/Mutations/login.ts
  src/graphql/User/Queries/getCurrentUser.ts
  src/models/User/Errors/UserNotFoundError.ts
  src/models/User/Repository.ts
  test/graphql/User/queries/getCurrentUser.test.ts
  test/models/User/Repository.test.ts
  tsconfig.json
Labels: fix

#228 Add separatedStatusLabel and statusLabel translation groups
  src/models/Translation/defaultTranslations.ts
Labels: feature

#231 Add jobSpecs translationGroup
  src/models/Translation/defaultTranslations.ts
Labels: refactor

#232 Feature/279 feed status label
  src/models/Translation/defaultTranslations.ts
Labels: feature

#235 Feature/282 get approved offers query
  .gitignore
  src/graphql/Applicant/Types/GraphQLApplicantType.ts
  src/graphql/Applicant/Types/index.ts
  src/graphql/Offer/Mutations/createOffer.ts
  src/graphql/Offer/Mutations/editOffer.ts
  src/graphql/Offer/Permissions.ts
  src/graphql/Offer/Queries/getApprovedOffers.ts
  src/graphql/Offer/Queries/index.ts
  src/graphql/Offer/Types/GraphQLOffer.ts
  src/migrations/20200405021050-create-applicant-type-enum.ts
  src/migrations/20200405021051-create-offer.ts
  src/models/Applicant/Errors/ApplicantWithNoCareersError.ts
  src/models/Applicant/Errors/index.ts
  src/models/Applicant/Model.ts
  src/models/Offer/Interface.ts
  src/models/Offer/Model.ts
  src/models/Offer/Repository.ts
  src/models/SequelizeModelValidators/isTargetApplicantType.ts
  src/seeders/constants/offers/devartis/offers/javaJunior.ts
  src/seeders/constants/offers/devartis/offers/javaSemiSenior.ts
  src/seeders/constants/offers/devartis/offers/rubyJunior.ts
  src/seeders/constants/offers/devartis/offers/rubySemiSenior.ts
  src/seeders/constants/offers/devartis/offers/rubySenior.ts
  src/seeders/constants/offers/mercadoLibre/offers/javaSenior.ts
  test/generators/Offer/index.ts
  test/generators/Offer/withObligatoryData.ts
  test/graphql/Offer/mutations/createOffer.test.ts
  test/graphql/Offer/mutations/editOffer.test.ts
  test/graphql/Offer/queries/getApprovedOffers.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Offer/Model.test.ts
  test/models/Offer/Repository.test.ts
  test/setup/AdminTask.ts
Labels: feature

#240 Feature/321 apply to offer permissions
  src/graphql/JobApplication/Mutations/saveJobApplication.ts
  src/models/JobApplication/Errors/OfferNotTargetedForApplicantError.ts
  src/models/JobApplication/Errors/index.ts
  src/models/JobApplication/Repository.ts
  src/models/Offer/Model.ts
  test/generators/Applicant/index.ts
  test/generators/JobApplication/index.ts
  test/generators/Offer/index.ts
  test/graphql/AdminTask/queries/getAdminTasks.test.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/JobApplication/mutations/updateJobApplicationApprovalStatus.test.ts
  test/graphql/JobApplication/queries/getJobApplicationByUuid.test.ts
  test/graphql/JobApplication/queries/getMyLatestJobApplications.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/models/AdminTask/Repository.test.ts
  test/models/JobApplication/JobApplicationApprovalEvent/Repository.test.ts
  test/models/JobApplication/Repository.test.ts
  test/models/Offer/Repository.test.ts
Labels: feature

#241 add admin translations of links in navbar
  src/models/Translation/defaultTranslations.ts
Labels: feature

#242 Allow admin to aprove offer targeted for the correct applicant they m…
  src/models/Offer/Repository.ts
  test/models/Offer/Repository.test.ts
Labels: feature

#244 Refactor getMyLatestJobApplications query to receive uuid
  src/graphql/JobApplication/Queries/getMyLatestJobApplications.ts
  src/graphql/Pagination/Types/GraphQLPaginatedInput.ts
  src/models/JobApplication/Repository.ts
  test/generators/JobApplication/index.ts
  test/graphql/JobApplication/queries/getMyLatestJobApplications.test.ts
  test/models/JobApplication/Repository.test.ts
Labels: refactor

#247 Feature/320 get offer
  src/graphql/Offer/Permissions.ts
  src/graphql/Offer/Queries/Errors/OfferNotVisibleByApplicantError.ts
  src/graphql/Offer/Queries/Errors/index.ts
  src/graphql/Offer/Queries/getOfferVisibleByCurrentApplicant.ts
  src/graphql/Offer/Queries/index.ts
  src/models/Offer/Errors/OfferNotFoundError.ts
  src/models/Offer/Errors/index.ts
  src/models/Offer/Repository.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOfferVisibleByCurrentApplicant.test.ts
  test/models/Offer/Repository.test.ts
Labels: feature

#248 Seeders/extension and graduados admins
  src/seeders/20200503190707-add-users.ts
  src/seeders/20200612002940-add-admins.ts
  src/seeders/constants/admins/extensionAdmin.ts
  src/seeders/constants/admins/graduadosAdmin.ts
  src/seeders/constants/admins/index.ts
  src/seeders/constants/uuids.ts
Labels: feature

#249 Feature/331 permissions
  src/models/Permissions/AdminPermissions/Permissions.ts
  src/models/Permissions/AdminPermissions/index.ts
  src/models/Permissions/ApplicantPermissions/Permissions.ts
  src/models/Permissions/ApplicantPermissions/index.ts
  src/models/Permissions/CompanyPermissions/Permissions.ts
  src/models/Permissions/CompanyPermissions/index.ts
  src/models/Permissions/index.ts
  test/models/Permissions/AdminPermissions/Permissions.test.ts
  test/models/Permissions/ApplicantPermissions/Permissions.test.ts
  test/models/Permissions/CompanyPermissions/Permissions.test.ts
Labels: feature

#250 cambio de permisos en getCompanies query
  src/graphql/Company/Permissions.ts
  test/graphql/Company/queries/getCompanies.test.ts
Labels: feature

#252 agregado de businessName a company (razon social)
  jest.config.js
  package.json
  src/graphql/Company/Mutations/createCompany.ts
  src/graphql/Company/Mutations/updateCurrentCompany.ts
  src/graphql/Company/Types/GraphQLCompany.ts
  src/migrations/20200129005352-create-companies-table.ts
  src/models/Company/Interface.ts
  src/models/Company/Model.ts
  src/models/SequelizeModelValidators/index.ts
  src/models/SequelizeModelValidators/isNotEmptyString.ts
  src/models/Translation/defaultTranslations.ts
  src/seeders/constants/companies/devartis.ts
  src/seeders/constants/companies/mercadoLibre.ts
  test/generators/BusinessName/index.ts
  test/generators/Company/withMinimumData.ts
  test/graphql/Company/mutations/createCompany.test.ts
  test/graphql/Company/queries/getCompanyByUuid.test.ts
  test/models/AdminTask/findAdminTasksQuery.test.ts
  test/models/AdminTask/groupTableNamesByColumn.test.ts
  test/models/Company/Model.test.ts
  test/models/Company/Repository.test.ts
  yarn.lock
Labels: feature

#251 Feature/319 current user
  src/models/CurrentUser/Model.ts
  src/models/CurrentUser/Roles/AdminRole/Role.ts
  src/models/CurrentUser/Roles/AdminRole/index.ts
  src/models/CurrentUser/Roles/ApplicantRole/Role.ts
  src/models/CurrentUser/Roles/ApplicantRole/index.ts
  src/models/CurrentUser/Roles/CompanyRole/Role.ts
  src/models/CurrentUser/Roles/CompanyRole/index.ts
  src/models/CurrentUser/Roles/Interface.ts
  src/models/CurrentUser/Roles/index.ts
  src/models/CurrentUser/index.ts
  src/models/Permissions/AdminPermissions/Permissions.ts
  src/models/Permissions/ApplicantPermissions/Permissions.ts
  src/models/Permissions/CompanyPermissions/Permissions.ts
  src/models/Permissions/Interface.ts
  src/models/Permissions/UserPermissions/Permissions.ts
  src/models/Permissions/UserPermissions/index.ts
  src/models/Permissions/index.ts
  test/models/CurrentUser/Model.test.ts
  test/models/CurrentUser/Roles/AdminRole/Role.test.ts
  test/models/CurrentUser/Roles/ApplicantRole/Role.test.ts
  test/models/CurrentUser/Roles/CompanyRole/Role.test.ts
  test/models/Permissions/UserPermissions/Permissions.test.ts
Labels: feature

#254 Feature/319 current user serializer
  src/models/CurrentUser/Builder.ts
  src/models/CurrentUser/Model.ts
  src/models/CurrentUser/index.ts
  test/models/CurrentUser/Build.test.ts
  test/models/CurrentUser/Model.test.ts
Labels: feature

#255 Use CurrentUser model in the graphql context
  src/JWT.ts
  src/graphql/AdminTask/Queries/getAdminTasks.ts
  src/graphql/Applicant/Mutations/updateApplicantApprovalStatus.ts
  src/graphql/Applicant/Mutations/updateCurrentApplicant.ts
  src/graphql/Company/Mutations/updateCompanyApprovalStatus.ts
  src/graphql/Company/Mutations/updateCurrentCompany.ts
  src/graphql/Context/AdminContext.ts
  src/graphql/Context/ApplicantContext.ts
  src/graphql/Context/CompanyContext.ts
  src/graphql/Context/UserContext.ts
  src/graphql/Context/graphqlContext.ts
  src/graphql/Context/index.ts
  src/graphql/JobApplication/Mutations/saveJobApplication.ts
  src/graphql/JobApplication/Mutations/updateJobApplicationApprovalStatus.ts
  src/graphql/JobApplication/Queries/getMyLatestJobApplications.ts
  src/graphql/Offer/Mutations/createOffer.ts
  src/graphql/Offer/Mutations/editOffer.ts
  src/graphql/Offer/Mutations/updateOfferApprovalStatus.ts
  src/graphql/Offer/Queries/getApprovedOffers.ts
  src/graphql/Offer/Queries/getMyOffers.ts
  src/graphql/Offer/Queries/getOfferVisibleByCurrentApplicant.ts
  src/graphql/Rules/isAdmin.ts
  src/graphql/Rules/isApplicant.ts
  src/graphql/Rules/isApprovedApplicant.ts
  src/graphql/Rules/isCompanyUser.ts
  src/graphql/Rules/isFromApprovedCompany.ts
  src/graphql/Translation/Queries/getTranslations.ts
  src/graphql/Translation/Queries/index.ts
  src/graphql/Translation/index.ts
  src/graphql/Translation/queries.ts
  src/graphql/User/Mutations/login.ts
  src/graphql/User/Mutations/logout.ts
  src/graphql/types.ts
  src/models/CurrentUser/Builder.ts
  src/models/CurrentUser/index.ts
  test/generators/TestClient/createApolloTestClient.ts
  test/graphql/ApolloTestClient.ts
  test/graphql/Translation/queries/getTranslations.test.ts
  test/graphql/User/mutations/login.test.ts
Labels: feature

#256 Add compiler options to avoid using unused statements
  src/graphql/Rules/isAdmin.ts
  src/graphql/Rules/isApplicant.ts
  src/graphql/Rules/isApprovedApplicant.ts
  src/graphql/Rules/isCompanyUser.ts
  src/graphql/Rules/isFromApprovedCompany.ts
  src/graphql/Rules/isUser.ts
  src/models/Permissions/AdminPermissions/Permissions.ts
  test/graphql/User/mutations/login.test.ts
  tsconfig.json
Labels: fix

#257 Feature/327 filter offer tasks
  src/models/AdminTask/Interfaces.ts
  src/models/AdminTask/Model.ts
  src/models/AdminTask/WhereClauseBuilder.ts
  src/models/AdminTask/findAdminTasksQuery.ts
  test/graphql/AdminTask/queries/getAdminTasks.test.ts
  test/models/AdminTask/Repository.test.ts
  test/models/AdminTask/WhereClauseBuilder.test.ts
  test/models/AdminTask/findAdminTasksQuery.test.ts
  test/setup/AdminTask.ts
Labels: feature

#258 Feature/319 get offer by UUID permissions
  src/graphql/Offer/Permissions.ts
  src/graphql/Offer/Queries/Errors/OfferNotVisibleByApplicantError.ts
  src/graphql/Offer/Queries/Errors/OfferNotVisibleByCurrentUserError.ts
  src/graphql/Offer/Queries/Errors/index.ts
  src/graphql/Offer/Queries/getOfferByUuid.ts
  src/graphql/Offer/Queries/getOfferVisibleByCurrentApplicant.ts
  src/graphql/Offer/Queries/index.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOfferVisibleByCurrentApplicant.test.ts
Labels: feature

#259 Move ApplicantType enum to Applicant directory
  src/graphql/Applicant/Types/GraphQLApplicantType.ts
  src/models/Applicant/Interface.ts
  src/models/Applicant/Model.ts
  src/models/JobApplication/Errors/OfferNotTargetedForApplicantError.ts
  src/models/Offer/Interface.ts
  src/models/Offer/Model.ts
  src/models/Offer/Repository.ts
  src/models/Permissions/ApplicantPermissions/Permissions.ts
  src/models/SequelizeModelValidators/isTargetApplicantType.ts
  src/seeders/constants/offers/devartis/offers/javaJunior.ts
  src/seeders/constants/offers/devartis/offers/javaSemiSenior.ts
  src/seeders/constants/offers/devartis/offers/rubyJunior.ts
  src/seeders/constants/offers/devartis/offers/rubySemiSenior.ts
  src/seeders/constants/offers/devartis/offers/rubySenior.ts
  src/seeders/constants/offers/mercadoLibre/offers/javaSenior.ts
  test/generators/Offer/index.ts
  test/generators/Offer/withObligatoryData.ts
  test/graphql/Offer/mutations/editOffer.test.ts
  test/graphql/Offer/queries/getApprovedOffers.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/JobApplication/Repository.test.ts
  test/models/Offer/Model.test.ts
  test/models/Offer/Repository.test.ts
Labels: refactor

#260 Fix/321 check user permission in the saveJobApplication mutation
  src/graphql/JobApplication/Mutations/saveJobApplication.ts
  src/models/JobApplication/Errors/OfferNotTargetedForApplicantError.ts
  src/models/JobApplication/Repository.ts
  src/models/Offer/Model.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/models/JobApplication/Repository.test.ts
  test/models/Offer/Repository.test.ts
Labels: fix

#261 Feature/327 offer moderation permission
  .prettierignore
  src/graphql/Offer/Mutations/updateOfferApprovalStatus.ts
  src/models/CurrentUser/Roles/AdminRole/Role.ts
  src/models/Offer/Errors/AdminCannotModerateOfferError.ts
  src/models/Offer/Errors/index.ts
  src/models/Offer/Repository.ts
  src/models/Offer/index.ts
  src/models/Permissions/AdminPermissions/Permissions.ts
  src/models/Permissions/ApplicantPermissions/Permissions.ts
  src/models/Permissions/CompanyPermissions/Permissions.ts
  src/models/Permissions/Interface.ts
  src/models/Permissions/UserPermissions/Permissions.ts
  test/generators/Admin/index.ts
  test/generators/Offer/index.ts
  test/graphql/Offer/mutations/updateOfferApprovalStatus.test.ts
  test/models/JobApplication/Repository.test.ts
  test/models/Offer/Repository.test.ts
  test/models/Permissions/AdminPermissions/Permissions.test.ts
  test/models/Permissions/ApplicantPermissions/Permissions.test.ts
  test/models/Permissions/CompanyPermissions/Permissions.test.ts
  test/models/Permissions/UserPermissions/Permissions.test.ts
Labels: feature

#263 Feature/338 filter applicants
  src/models/AdminTask/WhereClauseBuilder/TargetWhereClauseBuilder/ClauseBuilder.ts
  src/models/AdminTask/WhereClauseBuilder/TargetWhereClauseBuilder/index.ts
  src/models/AdminTask/WhereClauseBuilder/WhereClauseBuilder.ts
  src/models/AdminTask/WhereClauseBuilder/index.ts
  test/graphql/AdminTask/queries/getAdminTasks.test.ts
  test/models/AdminTask/Repository.test.ts
  test/models/AdminTask/WhereClauseBuilder/TargetWhereClauseBuilder/ClauseBuilder.test.ts
  test/models/AdminTask/WhereClauseBuilder/WhereClauseBuilder.test.ts
  test/models/AdminTask/findAdminTasksQuery.test.ts
  test/setup/Admin.ts
  test/setup/AdminTask.ts
  test/setup/Applicant.ts
  test/setup/Company.ts
  test/setup/JobApplication.ts
  test/setup/Offer.ts
Labels: feature

#265 Feature/339 filter job applications
  src/models/AdminTask/WhereClauseBuilder/ApplicantType.ts
  src/models/AdminTask/WhereClauseBuilder/JobApplicationTarget.ts
  src/models/AdminTask/WhereClauseBuilder/OfferTarget.ts
  src/models/AdminTask/WhereClauseBuilder/Status.ts
  src/models/AdminTask/WhereClauseBuilder/TargetWhereClauseBuilder/ClauseBuilder.ts
  src/models/AdminTask/WhereClauseBuilder/TargetWhereClauseBuilder/index.ts
  src/models/AdminTask/WhereClauseBuilder/UpdatedAt.ts
  src/models/AdminTask/WhereClauseBuilder/WhereClauseBuilder.ts
  src/models/AdminTask/WhereClauseBuilder/index.ts
  test/models/AdminTask/Repository.test.ts
  test/models/AdminTask/WhereClauseBuilder/ApplicantType.test.ts
  test/models/AdminTask/WhereClauseBuilder/JobApplicationTarget.test.ts
  test/models/AdminTask/WhereClauseBuilder/OfferTarget.test.ts
  test/models/AdminTask/WhereClauseBuilder/Status.test.ts
  test/models/AdminTask/WhereClauseBuilder/TargetWhereClauseBuilder/ClauseBuilder.test.ts
  test/models/AdminTask/WhereClauseBuilder/UpdatedAt.test.ts
  test/models/AdminTask/WhereClauseBuilder/WhereClauseBuilder.test.ts
  test/models/AdminTask/findAdminTasksQuery.test.ts
  test/setup/AdminTask.ts
  test/setup/Applicant.ts
  test/setup/JobApplication.ts
  test/setup/applicantVisibleBy.ts
Labels: feature

#268 Feature/324 apply to offer permissions
  src/models/Permissions/ApplicantPermissions/Permissions.ts
  test/generators/Offer/index.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/models/Permissions/ApplicantPermissions/Permissions.test.ts
Labels: feature

#267 Feature/281 filter application by status
  src/graphql/JobApplication/Queries/getMyLatestJobApplications.ts
  src/models/JobApplication/Interfaces.ts
  src/models/JobApplication/Repository.ts
  test/graphql/JobApplication/queries/getMyLatestJobApplications.test.ts
  test/models/JobApplication/Repository.test.ts
Labels: feature

#269 Use extension and graduados methods from AdminGenerator
  test/generators/Applicant/index.ts
  test/generators/Offer/index.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/graphql/Company/queries/getCompanies.test.ts
  test/graphql/Company/queries/getCompanyByUuid.test.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/Offer/mutations/createOffer.test.ts
  test/graphql/Offer/mutations/editOffer.test.ts
  test/graphql/Offer/queries/getApprovedOffers.test.ts
  test/graphql/Offer/queries/getMyOffers.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
  test/models/Applicant/ApplicantApprovalEvent/Repository.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Company/CompanyApprovalEvent/Repository.test.ts
  test/models/Company/Repository.test.ts
  test/models/JobApplication/JobApplicationApprovalEvent/Repository.test.ts
  test/models/JobApplication/Repository.test.ts
  test/models/Offer/OfferApprovalEvent/Repository.test.ts
  test/models/Offer/Repository.test.ts
  test/models/Permissions/UserPermissions/Permissions.test.ts
Labels: refactor
