Repository fiuba-laboral-v2/back-end, pull requests merged in 2020-08, with the labels that each got.

#170 Add secretary column in admin table
  src/migrations/20200609181508-create-secretary-enum.ts
  src/migrations/20200609181509-create-admins-table.ts
  src/models/Admin/Interface.ts
  src/models/Admin/Model.ts
  src/models/Admin/Repository.ts
  src/models/Admin/index.ts
  src/models/SequelizeModelValidators/index.ts
  src/models/SequelizeModelValidators/isSecretary.ts
  src/seeders/constants/admins/admin.ts
  test/generators/Admin/extensionAdminGenerator.ts
  test/generators/Admin/graduadosAdminGenerator.ts
  test/generators/Admin/index.ts
  test/generators/Admin/withCompleteData.ts
  test/graphql/AdminTask/queries/getAdminTasks.test.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/graphql/Company/queries/getCompanies.test.ts
  test/graphql/Company/queries/getCompanyByUuid.test.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/JobApplication/queries/getMyLatestJobApplications.test.ts
  test/graphql/Offer/mutations/createOffer.test.ts
  test/graphql/Offer/mutations/editOffer.test.ts
  test/graphql/Offer/queries/getMyOffers.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
  test/mocks/user.ts
  test/models/Admin/Model.test.ts
  test/models/Admin/Repository.test.ts
  test/models/AdminTask/Repository.test.ts
  test/models/Applicant/ApplicantApprovalEvent/Repository.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Company/CompanyApprovalEvent/Repository.test.ts
  test/models/Company/Repository.test.ts
Labels: feature

#169 Feature/233 soap service
  package.json
  src/config/index.ts
  src/config/services/FiubaUsersServiceConfig.ts
  src/config/services/index.ts
  src/services/FiubaUsers/Errors/AuthenticateFaultError.ts
  src/services/FiubaUsers/Errors/AuthenticateUnknownError.ts
  src/services/FiubaUsers/Errors/InvalidEmptyPasswordError.ts
  src/services/FiubaUsers/Errors/InvalidEmptyUsernameError.ts
  src/services/FiubaUsers/Errors/index.ts
  src/services/FiubaUsers/FiubaUsersApi/Api.ts
  src/services/FiubaUsers/FiubaUsersApi/RequestBodyBuilder.ts
  src/services/FiubaUsers/FiubaUsersApi/index.ts
  src/services/FiubaUsers/Interfaces.ts
  src/services/FiubaUsers/Service.ts
  src/services/FiubaUsers/index.ts
  test/services/FiubaUsers/FiubaUsersApi/Api.test.ts
  test/services/FiubaUsers/FiubaUsersApi/RequestBodyBuilder.test.ts
  test/services/FiubaUsers/FiubaUsersApi/RequestBodyMock.ts
  test/services/FiubaUsers/Service.test.ts
  yarn.lock
Labels: feature

#173 Fix/migrations approval event
  package.json
  src/migrations/20200609181510-create-company-approval-events-table.ts
  src/migrations/20200627223224-create-applicant-approval-events-table.ts
  src/migrations/tsconfig.json
Labels: fix

#174 Feature/246 users dni
  package.json
  src/migrations/20200204234523-create-users.ts
  src/models/SequelizeModelValidators/index.ts
  src/models/SequelizeModelValidators/optional.ts
  src/models/User/Interface.ts
  src/models/User/Model.ts
  test/models/User/Model.test.ts
  test/models/User/Repository.test.ts
  yarn.lock
Labels: feature

#172 Agregado de OfferApprovalEvent
  src/config/Database.ts
  src/graphql/Offer/Mutations/createOffer.ts
  src/migrations/20200101010101-create-approval-status-enum-type.ts
  src/migrations/20200405021051-create-offer.ts
  src/migrations/20200803230040-create-offers-approval-events-table.ts
  src/models/Offer/Model.ts
  src/models/Offer/OfferApprovalEvent/Interface.ts
  src/models/Offer/OfferApprovalEvent/Model.ts
  src/models/Offer/OfferApprovalEvent/index.ts
  src/models/index.ts
  test/models/JobApplication/Repository.test.ts
  test/models/Offer/Model.test.ts
  test/models/Offer/OfferApprovalEvent/Model.test.ts
Labels: feature

#177 Feature/247 user register soap service integration
  package.json
  src/graphql/Applicant/Mutations/saveApplicant.ts
  src/graphql/User/Mutations/login.ts
  src/graphql/User/Types/GraphQLUser.ts
  src/graphql/User/Types/GraphQLUserCreateInput.ts
  src/migrations/20200204234523-create-users.ts
  src/models/Applicant/Interface.ts
  src/models/Applicant/Repository.ts
  src/models/Applicant/index.ts
  src/models/Translation/defaultTranslations.ts
  src/models/User/Errors/FiubaUserNotFoundError.ts
  src/models/User/Errors/MissingDniError.ts
  src/models/User/Errors/index.ts
  src/models/User/Interface.ts
  src/models/User/Model.ts
  src/models/User/Repository.ts
  src/models/User/index.ts
  src/services/FiubaUsers/FiubaUsersApi/Api.ts
  src/services/FiubaUsers/FiubaUsersApi/RequestBodyBuilder.ts
  src/services/FiubaUsers/Interfaces.ts
  src/services/FiubaUsers/Service.ts
  src/services/index.ts
  test/generators/Applicant/index.ts
  test/generators/Applicant/withMinimumData.ts
  test/graphql/Applicant/mutations/saveApplicant.test.ts
  test/mocks/user.ts
  test/models/Applicant/Repository.test.ts
  test/models/Applicant/Section/Repository.test.ts
  test/models/User/Model.test.ts
  test/models/User/Repository.test.ts
  test/services/FiubaUsers/FiubaUsersApi/Api.test.ts
  test/services/FiubaUsers/FiubaUsersApi/RequestBodyBuilder.test.ts
  test/services/FiubaUsers/Service.test.ts
  tsconfig.json
  yarn.lock
Labels: feature

#180 Feature/247 user register
  src/models/Translation/defaultTranslations.ts
Labels: feature

#176 Add pagination to admin homescreen
  package.json
  src/config/PaginationConfig.ts
  src/graphql/AdminTask/Queries/getAdminTasks.ts
  src/graphql/AdminTask/Types/GraphQLPaginatedAdminTasks.ts
  src/graphql/Applicant/Mutations/saveApplicant.ts
  src/graphql/Offer/Queries/getMyOffers.ts
  src/graphql/Offer/Queries/getOffers.ts
  src/graphql/Offer/Types/GraphQLPaginatedOffers.ts
  src/graphql/User/Types/GraphQLUser.ts
  src/graphql/User/Types/GraphQLUserCreateInput.ts
  src/migrations/20200204234523-create-users.ts
  src/models/AdminTask/Interfaces.ts
  src/models/AdminTask/Repository.ts
  src/models/AdminTask/findAdminTasksQuery.ts
  src/models/Applicant/Repository.ts
  src/models/Offer/Repository.ts
  src/models/Translation/defaultTranslations.ts
  src/models/User/Model.ts
  src/models/User/Repository.ts
  src/services/FiubaUsers/FiubaUsersApi/Api.ts
  test/config/jest.setup.ts
  test/config/setupMocks.ts
  test/generators/Admin/extensionAdminGenerator.ts
  test/generators/Admin/graduadosAdminGenerator.ts
  test/generators/Applicant/index.ts
  test/graphql/AdminTask/queries/getAdminTasks.test.ts
  test/graphql/Applicant/mutations/updateCompanyApprovalStatus.test.ts
  test/graphql/Company/mutations/updateCompanyApprovalStatus.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
  test/mocks/config/PaginationConfig.ts
  test/models/AdminTask/Repository.test.ts
  test/models/AdminTask/findAdminTasksQuery.test.ts
  test/models/Company/CompanyApprovalEvent/Repository.test.ts
  test/models/Offer/Repository.test.ts
  test/models/User/Model.test.ts
  test/models/User/Repository.test.ts
  test/services/FiubaUsers/Service.test.ts
  tsconfig.json
  yarn.lock
Labels: feature

#181 Refactor/249 dni type
  package.json
  src/graphql/User/Types/GraphQLUser.ts
  src/graphql/User/Types/GraphQLUserCreateInput.ts
  src/migrations/20200204234523-create-users.ts
  src/models/SequelizeModelValidators/index.ts
  src/models/SequelizeModelValidators/optional.ts
  src/models/User/Errors/FiubaUserNotFoundError.ts
  src/models/User/Interface.ts
  src/models/User/Model.ts
  src/services/FiubaUsers/Interfaces.ts
  src/services/FiubaUsers/Service.ts
  test/generators/DNI/index.ts
  test/models/User/Model.test.ts
  test/models/User/Repository.test.ts
  test/services/FiubaUsers/FiubaUsersApi/RequestBodyBuilder.test.ts
  test/services/FiubaUsers/Service.test.ts
  yarn.lock
Labels: refactor

#183 Feature/253 fetch error
  src/services/FiubaUsers/Errors/FiubaUsersServiceFetchError.ts
  src/services/FiubaUsers/Errors/index.ts
  src/services/FiubaUsers/FiubaUsersApi/Api.ts
  src/services/FiubaUsers/Service.ts
  test/graphql/Applicant/mutations/updateCompanyApprovalStatus.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/services/FiubaUsers/FiubaUsersApi/Api.test.ts
  test/services/FiubaUsers/Service.test.ts
Labels: feature

#184 Hotfix: Catch TypeError on unexpected response format
  src/services/FiubaUsers/Errors/AuthenticateFaultError.ts
  test/services/FiubaUsers/FiubaUsersApi/Api.test.ts
Labels: fix

#185 Add graduate column for ApplicantCareer
  src/migrations/20200205200615-create-career-applicant-table.ts
  src/models/ApplicantCareer/Model.ts
  test/generators/Career/careerGenerator.ts
  test/generators/Career/index.ts
  test/graphql/Applicant/mutations/saveApplicant.test.ts
  test/graphql/Applicant/mutations/updateCurrentApplicant.test.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/graphql/Career/mutations/saveCareer.test.ts
  test/graphql/Career/queries/getCareerByCode.test.ts
  test/graphql/Career/queries/getCareers.test.ts
  test/graphql/Offer/mutations/createOffer.test.ts
  test/graphql/Offer/queries/getMyOffers.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/ApplicantCareer/Model.test.ts
  test/models/Career/Repository.test.ts
  test/models/CareerApplicant/Model.test.ts
  test/models/Offer/Repository.test.ts
Labels: feature

#186 Feature/206 applicant career is graduate
  src/graphql/Applicant/Mutations/saveApplicant.ts
  src/graphql/Applicant/Mutations/updateCurrentApplicant.ts
  src/graphql/Applicant/Types/GraphQLApplicant.ts
  src/graphql/Applicant/Types/GraphQLApplicantCareer.ts
  src/graphql/Applicant/Types/GraphQLCareerCredits.ts
  src/graphql/Applicant/Types/index.ts
  src/migrations/20200205200615-create-career-applicant-table.ts
  src/models/Applicant/Interface.ts
  src/models/ApplicantCareer/Model.ts
  src/models/ApplicantCareer/Repository.ts
  src/models/ApplicantCareer/Serializer.ts
  src/seeders/constants/applicants/aldana.ts
  src/seeders/constants/applicants/sebastian.ts
  test/graphql/Applicant/mutations/saveApplicant.test.ts
  test/graphql/Applicant/mutations/updateCurrentApplicant.test.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/ApplicantCareer/Model.test.ts
Labels: feature

#187 Refactor/applicant career graphql type
  src/graphql/Applicant/Mutations/saveApplicant.ts
  src/graphql/Applicant/Mutations/updateCurrentApplicant.ts
  src/graphql/Applicant/Types/GraphQLApplicant.ts
  src/graphql/Applicant/Types/GraphQLApplicantCareer.ts
  src/graphql/Applicant/Types/GraphQLApplicantCareerInput.ts
  src/graphql/Applicant/Types/index.ts
  src/models/ApplicantCareer/Serializer.ts
  src/models/ApplicantCareer/index.ts
  test/graphql/Applicant/mutations/saveApplicant.test.ts
  test/graphql/Applicant/mutations/updateCurrentApplicant.test.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
Labels: refactor

#190 Move ApplicantCareer folder inside Applicant
  src/models/Applicant/ApplicantCareer/Errors/ApplicantCareerNotFound.ts
  src/models/Applicant/ApplicantCareer/Errors/index.ts
  src/models/Applicant/ApplicantCareer/Model.ts
  src/models/Applicant/ApplicantCareer/Repository.ts
  src/models/Applicant/ApplicantCareer/index.ts
  src/models/Applicant/Repository.ts
  src/models/index.ts
  test/models/Applicant/ApplicantCareer/Model.test.ts
  test/models/Applicant/Repository.test.ts
Labels: refactor

#192 Feature/206 applicant career progress
  src/graphql/Applicant/Types/GraphQLApplicantCareer.ts
  src/graphql/Applicant/Types/GraphQLApplicantCareerInput.ts
  src/migrations/20200205200615-create-applicant-careers-table.ts
  src/models/Applicant/ApplicantCareer/Errors/ApplicantCareerNotFound.ts
  src/models/Applicant/ApplicantCareer/Errors/ForbiddenApprovedSubjectCountError.ts
  src/models/Applicant/ApplicantCareer/Errors/ForbiddenCurrentCareerYearError.ts
  src/models/Applicant/ApplicantCareer/Errors/MissingApprovedSubjectCountError.ts
  src/models/Applicant/ApplicantCareer/Errors/MissingCurrentCareerYearError.ts
  src/models/Applicant/ApplicantCareer/Errors/index.ts
  src/models/Applicant/ApplicantCareer/Interfaces.ts
  src/models/Applicant/ApplicantCareer/Model.ts
  src/models/Applicant/ApplicantCareer/Repository.ts
  src/models/Applicant/ApplicantCareer/index.ts
  src/models/Applicant/Interface.ts
  src/models/SequelizeModelValidators/index.ts
  src/models/SequelizeModelValidators/optional.ts
  src/models/Translation/defaultTranslations.ts
  src/seeders/constants/applicants/aldana.ts
  src/seeders/constants/applicants/sebastian.ts
  test/generators/interfaces.ts
  test/graphql/Applicant/mutations/saveApplicant.test.ts
  test/graphql/Applicant/mutations/updateCurrentApplicant.test.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/models/Applicant/ApplicantCareer/Model.test.ts
  test/models/Applicant/ApplicantCareer/Repository.test.ts
  test/models/Applicant/Repository.test.ts
Labels: feature

#195 Feature/206 careers input
  src/models/Applicant/ApplicantCareer/Repository.ts
  src/models/Translation/defaultTranslations.ts
  test/models/Applicant/ApplicantCareer/Repository.test.ts
  test/models/Applicant/Repository.test.ts
Labels: feature

#191 Add Offers in Admin Tasks
  src/graphql/AdminTask/Queries/getAdminTasks.ts
  src/graphql/AdminTask/Types/GraphQLAdminTask.ts
  src/graphql/Offer/Types/GraphQLOffer.ts
  src/models/AdminTask/Interfaces.ts
  src/models/AdminTask/Model.ts
  src/models/AdminTask/findAdminTasksQuery.ts
  src/models/AdminTask/groupTableNamesByColumn.ts
  src/models/Offer/Repository.ts
  test/generators/Offer/index.ts
  test/graphql/AdminTask/queries/getAdminTasks.test.ts
  test/models/AdminTask/Repository.test.ts
  test/models/AdminTask/findAdminTasksQuery.test.ts
  test/models/AdminTask/groupTableNamesByColumn.test.ts
  test/models/Offer/Repository.test.ts
Labels: feature

#196 Add translations to careersDetail translationGroup
  src/models/Translation/defaultTranslations.ts
Labels: feature

#199 Refactor/remove company mock
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/models/Company/Repository.test.ts
  test/models/Company/mocks.ts
  test/models/CompanyPhoneNumber/Repository.test.ts
  test/models/CompanyUser/Repository.test.ts
  test/models/User/mocks.ts
Labels: refactor

#198 Feature/206 remove career credits
  src/graphql/Applicant/Types/GraphQLApplicantCareer.ts
  src/graphql/Career/Mutations/index.ts
  src/graphql/Career/Mutations/saveCareer.ts
  src/graphql/Career/Queries/getCareerByCode.ts
  src/graphql/Career/Queries/getCareers.ts
  src/graphql/Career/Queries/index.ts
  src/graphql/Career/Types/GraphQLCareer.ts
  src/graphql/Career/Types/index.ts
  src/graphql/Career/index.ts
  src/graphql/Career/mutations.ts
  src/graphql/Career/queries.ts
  src/graphql/Offer/Types/GraphQLOffer.ts
  src/graphql/types.ts
  src/migrations/20200203222832-create-careers-table.ts
  src/models/Career/Errors/CareersNotFound.ts
  src/models/Career/Errors/CareersNotFoundError.ts
  src/models/Career/Errors/index.ts
  src/models/Career/Interface.ts
  src/models/Career/Model.ts
  src/models/Career/Repository.ts
  src/models/Career/Serializer.ts
  src/models/Career/index.ts
  src/seeders/20200503163557-add-careers.ts
  test/generators/Career/careerData.ts
  test/graphql/Applicant/mutations/saveApplicant.test.ts
  test/graphql/Applicant/mutations/updateCurrentApplicant.test.ts
  test/graphql/Applicant/queries/getApplicant.test.ts
  test/graphql/Applicant/queries/getApplicants.test.ts
  test/graphql/Career/mutations/saveCareer.test.ts
  test/graphql/Career/queries/getCareerByCode.test.ts
  test/graphql/Career/queries/getCareers.test.ts
  test/graphql/Offer/mutations/createOffer.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/models/Career/Model.test.ts
  test/models/Career/Repository.test.ts
Labels: feature

#201 Feature/221 job application status
  src/migrations/20200412205326-create-job-applications-table.ts
  src/models/JobApplication/Model.ts
  test/models/JobApplication/Model.test.ts
  test/models/JobApplication/Repository.test.ts
Labels: feature

#202 Refactor OffersGenerator
  test/generators/GenericGenerator/index.ts
  test/generators/Offer/index.ts
  test/graphql/AdminTask/queries/getAdminTasks.test.ts
  test/graphql/JobApplication/mutations/saveJobApplication.test.ts
  test/graphql/JobApplication/queries/getMyLatestJobApplications.test.ts
  test/graphql/Offer/mutations/createOffer.test.ts
  test/graphql/Offer/mutations/editOffer.test.ts
  test/graphql/Offer/queries/getMyOffers.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/graphql/Offer/queries/getOffers.test.ts
  test/models/AdminTask/Repository.test.ts
  test/models/JobApplication/Repository.test.ts
  test/models/Offer/Repository.test.ts
Labels: refactor

#204 Feature/221 job application update status
  src/models/JobApplication/Errors/JobApplicationNotFoundError.ts
  src/models/JobApplication/Errors/index.ts
  src/models/JobApplication/Interfaces.ts
  src/models/JobApplication/Repository.ts
  src/models/JobApplication/index.ts
  test/models/JobApplication/Repository.test.ts
Labels: feature

#206 Feature/221 job application approval event
  src/config/Database.ts
  src/config/index.ts
  src/index.ts
  src/migrations/20200817224338-create-job-application-approval-events-table.ts
  src/models/Admin/Repository.ts
  src/models/AdminTask/Repository.ts
  src/models/Applicant/Repository.ts
  src/models/Career/Repository.ts
  src/models/Company/Repository.ts
  src/models/JobApplication/JobApplicationsApprovalEvent/Interfaces.ts
  src/models/JobApplication/JobApplicationsApprovalEvent/Model.ts
  src/models/JobApplication/JobApplicationsApprovalEvent/Repository.ts
  src/models/JobApplication/JobApplicationsApprovalEvent/index.ts
  src/models/Offer/Repository.ts
  src/models/Offer/index.ts
  src/models/index.ts
  test/config/setupDatabase.ts
  test/models/Applicant/ApplicantApprovalEvent/Model.test.ts
  test/models/Applicant/Model.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/JobApplication/JobApplicationApprovalEvent/Model.test.ts
  test/models/JobApplication/JobApplicationApprovalEvent/Repository.test.ts
  test/models/JobApplication/Model.test.ts
  test/models/JobApplication/Repository.test.ts
  test/models/Offer/Model.test.ts
  test/models/Offer/Repository.test.ts
  tsconfig.json
Labels: feature

#207 Feature/238 target applicant type
  src/graphql/Offer/Mutations/createOffer.ts
  src/graphql/Offer/Types/GraphQLOffer.ts
  src/graphql/Offer/Types/GraphQLTargetApplicantType.ts
  src/migrations/20200405021050-create-applicant-target-type-enum.ts
  src/migrations/20200405021051-create-offer.ts
  src/models/Offer/Interface.ts
  src/models/Offer/Model.ts
  src/models/Offer/index.ts
  src/models/SequelizeModelValidators/index.ts
  src/models/SequelizeModelValidators/isTargetApplicantType.ts
  src/models/Translation/defaultTranslations.ts
  src/seeders/20200503190710-add-offers.ts
  src/seeders/constants/offers/javaSemiSenior.ts
  src/seeders/constants/offers/javaSenior.ts
  src/seeders/tsconfig.json
  test/generators/Offer/index.ts
  test/generators/Offer/withObligatoryData.ts
  test/graphql/Offer/mutations/createOffer.test.ts
  test/graphql/Offer/mutations/editOffer.test.ts
  test/graphql/Offer/queries/getOfferByUuid.test.ts
  test/models/AdminTask/findAdminTasksQuery.test.ts
  test/models/Offer/Model.test.ts
  test/models/Offer/Repository.test.ts
Labels: feature

#208 Feature/238 edit offer
  src/graphql/Offer/Mutations/editOffer.ts
  test/graphql/Offer/mutations/editOffer.test.ts
  test/models/Offer/Repository.test.ts
Labels: feature

#209 Add offerTargetApplicantType translationGroup
  src/models/Translation/defaultTranslations.ts
Labels: feature

#211 Feature/seeders
  src/seeders/20200503190710-add-offers.ts
  src/seeders/constants/applicants/sebastian.ts
  src/seeders/constants/offers/devartis/description.ts
  src/seeders/constants/offers/devartis/index.ts
  src/seeders/constants/offers/devartis/offers/index.ts
  src/seeders/constants/offers/devartis/offers/javaJunior.ts
  src/seeders/constants/offers/devartis/offers/javaSemiSenior.ts
  src/seeders/constants/offers/devartis/offers/rubyJunior.ts
  src/seeders/constants/offers/devartis/offers/rubySemiSenior.ts
  src/seeders/constants/offers/devartis/offers/rubySenior.ts
  src/seeders/constants/offers/devartis/sections.ts
  src/seeders/constants/offers/index.ts
  src/seeders/constants/offers/javaSemiSenior.ts
  src/seeders/constants/offers/mercadoLibre/index.ts
  src/seeders/constants/offers/mercadoLibre/offers/index.ts
  src/seeders/constants/offers/mercadoLibre/offers/javaSenior.ts
  src/seeders/constants/uuids.ts
Labels: feature

#212 Rename translations
  src/models/Translation/defaultTranslations.ts
Labels: refactor

#213 Add toEqualObjectContaining customMatcher
  test/config/customMatchers/index.ts
  test/config/customMatchers/toBeObjectContaining.ts
  test/graphql/Career/mutations/saveCareer.test.ts
  test/graphql/User/mutations/login.test.ts
  test/models/Applicant/ApplicantCareer/Model.test.ts
  test/models/Applicant/Repository.test.ts
  test/models/Career/Model.test.ts
  test/models/JobApplication/JobApplicationApprovalEvent/Model.test.ts
  test/models/Offer/Model.test.ts
  test/models/Offer/Repository.test.ts
  test/types/index.d.ts
Labels: feature

#218 Feature/265 job application admin task
  src/models/AdminTask/Model.ts
  src/models/AdminTask/WhereClauseBuilder.ts
  src/models/AdminTask/findAdminTasksQuery.ts
  test/generators/JobApplication/index.ts
  test/graphql/JobApplication/mutations/updateJobApplicationApprovalStatus.test.ts
  test/models/AdminTask/Repository.test.ts
  test/models/AdminTask/WhereClauseBuilder.test.ts
  test/models/AdminTask/findAdminTasksQuery.test.ts
  test/models/AdminTask/groupTableNamesByColumn.test.ts
  test/models/JobApplication/JobApplicationApprovalEvent/Repository.test.ts
  test/models/JobApplication/Repository.test.ts
Labels: feature

#219 Feature/265 job application admin task graphql
  src/graphql/AdminTask/Types/GraphQLAdminTask.ts
  test/generators/Admin/extensionAdminGenerator.ts
  test/generators/Admin/graduadosAdminGenerator.ts
  test/graphql/AdminTask/queries/getAdminTasks.test.ts
  test/models/AdminTask/Repository.test.ts
  test/setup/AdminTask.ts
  tsconfig.json
Labels: feature

#220 Add jobApplicationIconTitle to typeFilterMenu translationGroup
  src/models/Translation/defaultTranslations.ts
Labels: feature

#223 Feature/266 job appliation
  src/graphql/JobApplication/Permissions.ts
  src/graphql/JobApplication/Queries/getJobApplicationByUuid.ts
  src/graphql/JobApplication/Queries/index.ts
  src/graphql/JobApplication/Types/GraphQLJobApplication.ts
  src/models/Translation/defaultTranslations.ts
  test/graphql/JobApplication/queries/getJobApplicationByUuid.test.ts
  test/graphql/JobApplication/queries/getMyLatestJobApplications.test.ts
Labels: feature
